# Generated by Django 2.0 on 2017-12-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171214_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='caption',
            field=models.CharField(default='hello', max_length=200),
            preserve_default=False,
        ),
    ]
