# Generated by Django 2.0 on 2017-12-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
