# Generated by Django 2.0 on 2017-12-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20171220_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
