# Generated by Django 2.0 on 2018-01-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20171221_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='topic',
            field=models.CharField(blank=True, choices=[('', ''), ('Sports', 'Sports'), ('Politics', 'Politics'), ('Programming', 'Programming'), ('Weather', 'Weather')], max_length=1),
        ),
    ]
