# Generated by Django 2.0 on 2018-01-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_document_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='topic',
            field=models.CharField(blank=True, choices=[('', ''), ('Sports', 'Sports'), ('Politics', 'Politics'), ('Programming', 'Programming'), ('Weather', 'Weather')], max_length=1),
        ),
    ]
