# Generated by Django 2.0 on 2018-01-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_video_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='topic',
            field=models.CharField(blank=True, choices=[('', ''), ('Sports', 'Sports'), ('Politics', 'Politics'), ('Programming', 'Programming'), ('Weather', 'Weather')], max_length=16),
        ),
        migrations.AlterField(
            model_name='video',
            name='topic',
            field=models.CharField(blank=True, choices=[('', ''), ('Sports', 'Sports'), ('Politics', 'Politics'), ('Programming', 'Programming'), ('Weather', 'Weather')], max_length=16),
        ),
    ]
