# Generated by Django 2.0 on 2018-01-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20180104_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Jo', max_length=18),
            preserve_default=False,
        ),
    ]
